# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:  
  name: Default 

#trigger: none 

trigger:
- main

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'


steps: 
- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack project'
  inputs:
    command: 'pack'
    projects: '**/*.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    configuration: $(buildConfiguration)
    includeSymbols: false

- task: DotNetCoreCLI@2
  displayName: 'Push package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'dotnet_hellothere_artifacts'
