trigger:
- main

jobs:
- job: Job1
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1
    name: 'NugetToolInstaller'
    displayName: 'Nuget tool installer'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'

  #- task: DotNetCoreCLI@2
  #  inputs:
  #    command: 'pack'
  #    packagesToPack: '**/*.csproj'
  #    versioningScheme: 'off'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      zipAfterPublish: false